/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("lab8.kotlin-application-conventions")
}

dependencies {
    implementation(project(":shared"))

}

application {
    // Define the main class for the application.
    mainClass.set("lab8.synchronizer.AppKt")
}
