package lab5.entities.vehicle

import lab5.entities.ValidationException


/**
 * Аннотация для автогенерируемых полей
 */
@Target(AnnotationTarget.FIELD)
annotation class Autogenerated

/**
 * Дата-класс транспорта
 */
data class Vehicle(
    @Autogenerated val id: Int,
    val name: String,
    val coordinates: Coordinates,
    @Autogenerated val creationDate: java.time.LocalDate,
    val enginePower: Double,
    val type: VehicleType?,
    val fuelType: FuelType,
) {
    /**
     * Функция, валидирующая Vehicle
     * @throws ValidationException если хотя бы одно из полей невалидно
     */
    fun validate() {
        if(id <= 0) {
            throw ValidationException("id", "should be greater than 0")
        }
        if(name.isEmpty()) {
            throw ValidationException("name", "should not be empty")
        }
        if(enginePower <= 0) {
            throw ValidationException("enginePower", "should be greater than 0")
        }
        coordinates.validate()
    }

    /**
     * Конвертирует в CSV
     */
    fun toCsv(): String {
        return "$id,${name.replace(",", "\\,")},${coordinates.x},${coordinates.y},$creationDate,$enginePower,$type,$fuelType"
    }
}