@startuml
entity Ученый {
  **PK** Имя
}

entity Фонд {
  **PK** ИД
  Владелец
}

entity Существо {
    **PK** Название
}

entity Клетка {
    **PK** Хранимое животное
}

entity Переговоры {
    **PK** Время проведения
}

entity Действие {
    **PK** Описание
}

entity Вещь {
    **PK** Описание
}


Ученый ||--o{ Фонд: владение
Существо ||--|| Клетка: находится в
Клетка |o--o| Вещь: накрыта
Действие }o--o{ Клетка: субъект действия
Действие }o--o{ Вещь: субъект действия

Ученый }|--o{ Существо: создатель
Ученый }|--o{ Переговоры: участник
Клетка }o--o{ Вещь: похожа на
Действие }o--o{ Ученый: деятель
Действие }o--o{ Переговоры: на каких переговорах

@enduml