SCIENTISTS: {
  shape: sql_table
  ID: SERIAL {constraint: primary_key}
  NAME: VARCHAR(50)
}

CREATURES: {
  shape: sql_table
  ID: SERIAL {constraint: primary_key}
  NAME: VARCHAR(50)
}

CAGES: {
  shape: sql_table
  ID: SERIAL {constraint: primary_key}
  CREATURE_ID: INTEGER {constraint: foreign_key}
}

FUNDS: {
  shape: sql_table
  ID: SERIAL {constraint: primary_key}
  OWNER_ID: INTEGER {constraint: foreign_key}
}

NEGOTIATIONS: {
  shape: sql_table
  ID: SERIAL {constraint: primary_key}
  START: TIMESTAMP
  END: TIMESTAMP
}

ACTIONS: {
  shape: sql_table
  ID: SERIAL {constraint: primary_key}
  DESCRIPTION: TEXT
}

THINGS: {
  shape: sql_table
  ID: SERIAL {constraint: primary_key}
  DESCRIPTION: TEXT
}

CAGE_LOOKS_LIKE: {
  shape: sql_table
  CAGE_ID: INTEGER {constraint: foreign_key}
  THING_ID: INTEGER {constraint: foreign_key}
}

ACTION_SUBJECT: {
  shape: sql_table
  ACTION_ID: INTEGER {constraint: foreign_key}
  SCIENTIST_ID: INTEGER {constraint: foreign_key}
}

NEGOTIATION_ACTIONS: {
  shape: sql_table
  ACTION_ID: INTEGER {constraint: foreign_key}
  NEG_ID: INTEGER {constraint: foreign_key}
}

ACTION_CAGE_OBJECT: {
  shape: sql_table
  ACTION_ID: INTEGER {constraint: foreign_key}
  CAGE_ID: INTEGER {constraint: foreign_key}
}

ACTION_THING_OBJECT: {
  shape: sql_table
  ACTION_ID: INTEGER {constraint: foreign_key}
  THING_ID: INTEGER {constraint: foreign_key}
}

NEGOTIATION_PARTICIPANTS: {
  shape: sql_table
  NEG_ID: INTEGER {constraint: foreign_key}
  SCIENTIST_ID: INTEGER {constraint: foreign_key}
}


CREATURE_CREATORS: {
  shape: sql_table
  SCIENTIST_ID: INTEGER {constraint: foreign_key}
  CREATURE_ID: INTEGER {constraint: foreign_key}
}

SCIENTISTS.ID <-> CREATURE_CREATORS.SCIENTIST_ID {
  target-arrowhead: {
    shape: cf-many
  }
  source-arrowhead: {
    shape: cf-one-required
  }
}

CREATURE_CREATORS.SCIENTIST_ID <-> CREATURES.ID {
  target-arrowhead: {
    shape: cf-one-required
  }
  source-arrowhead: {
    shape: cf-many-required
  }
}

FUNDS.OWNER_ID <-> SCIENTISTS.ID {
  target-arrowhead: {
    shape: cf-one-required
  }
  source-arrowhead: {
    shape: cf-many
  }
}

NEGOTIATIONS.ID <-> NEGOTIATION_PARTICIPANTS.NEG_ID {
  source-arrowhead: {
    shape: cf-one-required
  }
  target-arrowhead: {
    shape: cf-many-required
  }
}
NEGOTIATION_PARTICIPANTS.SCIENTIST_ID <-> SCIENTISTS.ID {
  target-arrowhead: {
    shape: cf-one-required
  }
  source-arrowhead: {
    shape: cf-many
  }
}

ACTIONS.ID <-> ACTION_SUBJECT.ACTION_ID  {
  target-arrowhead: {
    shape: cf-many
  }
  source-arrowhead: {
    shape: cf-one
  }
}
ACTION_SUBJECT.SCIENTIST_ID <-> SCIENTISTS.ID {
  target-arrowhead: {
    shape: cf-many
  }
  source-arrowhead: {
    shape: cf-one
  }
}

ACTIONS.ID <-> NEGOTIATION_ACTIONS.ACTION_ID {
  target-arrowhead: {
    shape: cf-many
  }
  source-arrowhead: {
    shape: cf-one
  }
}

NEGOTIATIONS.ID <-> NEGOTIATION_ACTIONS.NEG_ID {
  target-arrowhead: {
    shape: cf-many
  }
  source-arrowhead: {
    shape: cf-one
  }
}

CAGES.CREATURE_ID <-> CREATURES.ID {
  target-arrowhead: {
    shape: cf-one-required
  }
  source-arrowhead: {
    shape: cf-one-required
  }
}

CAGES.ID <-> THINGS.ID: накрыта {
  target-arrowhead: {
    shape: cf-one
  }
  source-arrowhead: {
    shape: cf-one
  }
}

CAGES.ID <-> CAGE_LOOKS_LIKE.CAGE_ID {
  target-arrowhead: {
    shape: cf-many
  }
  source-arrowhead: {
    shape: cf-one
  }
}

THINGS.ID <-> CAGE_LOOKS_LIKE.CAGE_ID {
  target-arrowhead: {
    shape: cf-many
  }
  source-arrowhead: {
    shape: cf-one
  }
}

ACTIONS.ID <-> ACTION_CAGE_OBJECT.ACTION_ID {
  target-arrowhead: {
    shape: cf-many
  }
  source-arrowhead: {
    shape: cf-one
  }
}

CAGES.ID <-> ACTION_CAGE_OBJECT.CAGE_ID {
  target-arrowhead: {
    shape: cf-many
  }
  source-arrowhead: {
    shape: cf-one
  }
}

ACTIONS.ID <-> ACTION_THING_OBJECT.ACTION_ID {
  target-arrowhead: {
    shape: cf-many
  }
  source-arrowhead: {
    shape: cf-one
  }
}

THINGS.ID <-> ACTION_THING_OBJECT.THING_ID {
  target-arrowhead: {
    shape: cf-many
  }
  source-arrowhead: {
    shape: cf-one
  }
}
