/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("lab8.kotlin-application-conventions")
}

dependencies {
    implementation(project(":shared"))
    // https://mvnrepository.com/artifact/org.postgresql/postgresql
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4")
    implementation("com.zaxxer:HikariCP:5.0.1")
    implementation("org.postgresql:postgresql:42.2.27")
}

application {
    // Define the main class for the application.
    mainClass.set("lab8.lb.AppKt")
}
