/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package lab5

import lab5.cli.CLIHandler
import lab5.repositories.VehicleRepository
import lab5.repositories.csv.VehicleCsvRepository
import java.io.BufferedReader
import java.io.BufferedWriter
import java.io.FileNotFoundException
import java.io.InputStreamReader
import java.io.OutputStreamWriter

fun main() {
    val inputStream = System.`in`
    val reader = BufferedReader(InputStreamReader(inputStream))

    val outputStream = System.out
    val writer = BufferedWriter(OutputStreamWriter(outputStream))

    val filename = System.getenv("FILENAME")
    val repository: VehicleRepository = VehicleCsvRepository(filename)
    if(filename.isNotEmpty()) {
        try {
            repository.loadData()
        }
        catch(e: FileNotFoundException) {
            writer.write("No file $filename. No data was loaded.\n")
            writer.flush()
        }
        catch(e: SecurityException) {
            writer.write("Not enough rights to open $filename. No data was loaded.\n")
            writer.flush()
        }
        catch(e: Exception) {
            writer.write("Can't open file $filename. Error: $e\n")
        }
    }



    val handler = CLIHandler(repository, reader, writer)

    handler.start()
}
