/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("lab8.kotlin-application-conventions")
}

dependencies {
    implementation(project(":shared"))
    // https://mvnrepository.com/artifact/org.postgresql/postgresql
    implementation("org.postgresql:postgresql:42.2.27")
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.8.10")

    // https://mvnrepository.com/artifact/com.zaxxer/HikariCP
    implementation("com.zaxxer:HikariCP:5.0.1")

    // https://mvnrepository.com/artifact/io.prometheus/simpleclient
    implementation("io.prometheus:simpleclient:0.16.0")

    // https://mvnrepository.com/artifact/io.prometheus/simpleclient_hotspot
    implementation("io.prometheus:simpleclient_hotspot:0.16.0")

    // https://mvnrepository.com/artifact/io.prometheus/simpleclient_httpserver
    implementation("io.prometheus:simpleclient_httpserver:0.16.0")

}

application {
    // Define the main class for the application.
    mainClass.set("lab8.server.AppKt")
}
