/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.itmo

import org.itmo.pokemons.*
import ru.ifmo.se.pokemon.Battle;
import ru.ifmo.se.pokemon.Pokemon

fun main() {
    val b = Battle();
    b.addAlly(Jirachi("Балакшин", 50))
    b.addAlly(Snubbull("Клименков", 50))
    b.addAlly(Granbull("Письмак", 50))
    b.addFoe(Sewaddle("Пастор", 50))
    b.addFoe(Swadloon("Карпов", 50))
    b.addFoe(Leavanny("Зураб Леванович", 50))
    b.go();
}
