ALTER TABLE SCIENTISTS ADD COLUMN LAST_UPDATE_TIMESTAMP TIMESTAMP;
ALTER TABLE SCIENTISTS ADD COLUMN LAST_UPDATE_BY TEXT;

CREATE FUNCTION cool_trigger() RETURNS trigger AS $cool_trigger$
  BEGIN
    NEW.LAST_UPDATE_TIMESTAMP := current_timestamp;
    NEW.LAST_UPDATE_BY := current_user;
    RETURN NEW;
  END;
$cool_trigger$ LANGUAGE plpgsql;

CREATE TRIGGER cool_trigger BEFORE UPDATE ON SCIENTISTS
  FOR EACH ROW EXECUTE PROCEDURE cool_trigger();
