Пользователь: {
  shape: person
}

Контент-мейкер: {
  shape: person
}

Пользователь <- Контент-мейкер: <<extends>>
Пользователь -- "vk.com".Регистрация
Пользователь -- "vk.com".Вход в систему
Пользователь -- "vk.com".Блокировка нежелательных пользователей
Пользователь -- "vk.com".Отправка сообщений

"vk.com": {
  Вход в систему <- Просмотр ленты новостей: <<includes>> {
    style: {
      stroke-dash: 3
    }
  }

  Вход в систему <- Оформление своей страницы: <<includes>> {
    style: {
      stroke-dash: 3
    }
  }

  Вход в систему <- Создание беседы: <<includes>> {
    style: {
      stroke-dash: 3
    }
  }
}
