/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.itmo.lab3

import org.itmo.lab3.characters.Donut
import org.itmo.lab3.characters.Dunno
import org.itmo.lab3.planets.Earth
import org.itmo.lab3.planets.Moon
import org.itmo.lab3.spaceships.Spaceship
import org.itmo.lab3.spaceships.rocket.Rocket

/**
  * Незнайка поднялся под потолок кабины и, прильнув к верхнему иллюминатору, принялся разглядывать поверхность Луны.
 * Теперь Луна была видна так, как бывает видна в телескоп с Земли, и даже лучше.
 * На ее поверхности вполне хорошо можно было разглядеть и горные цепи, и лунные цирки, и глубокие трещины или разломы.
 * Пончик нехотя поднялся кверху и стал исподлобья поглядывать в иллюминатор.
 * То, что он увидел, не принесло ему облегчения.
 * Он заметил, что Луна теперь не стояла на месте, а приближалась с заметной скоростью.
 * Сначала она была видна как огромный, величиной с полнеба, сверкающий круг.
 * Мало-помалу этот круг разрастался и в конце концов заполнил собой все небо.
 * Теперь, куда ни глянь, во все стороны простиралась поверхность Луны с опрокинутыми вверх ногами горными цепями,
 * лунными кратерами и долинами.
 * Все это угрожающе висело над головой и было уже так близко, что казалось, стоит только протянуть руку,
 * и можно потрогать верхушку какой-нибудь лунной горы.
  */
fun main() {
    val rocket: Spaceship = Rocket(arrayOf(Dunno(), Donut()), 1500.0)
    val moon = Moon()

    rocket.getCrewMember(0).getUp()
    rocket.getCrewMember(0).look(rocket.getIlluminator(), moon)
    rocket.getCrewMember(1).getUp()
    rocket.getCrewMember(1).look(rocket.getIlluminator(), moon)
    println("Скорость сближения с Луной: ${rocket.calcApproachSpeed(moon)}")
    rocket.getCrewMember(1).modifyRelief(0.0)
    println("Размер Луны: ${moon.getSizeComparedToSky()} неба")
    println("Размер Луны: ${moon.getSizeComparedToSky()} неба")
    val everythingAround = rocket.getIlluminator().getSeenObjects(moon)
    println("Вокруг видно: $everythingAround")
}
