/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.itmo.lab4

import io.mockk.every
import io.mockk.mockk
import io.mockk.verify
import org.itmo.lab4.characters.Character
import org.itmo.lab4.characters.Donut
import org.itmo.lab4.look.context.LookContext
import org.itmo.lab4.look.looker.Looker
import org.itmo.lab4.planets.Moon
import org.itmo.lab4.spaceships.rocket.Rocket
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class TestLook {
    @Test fun getSeenObjectsTest() {
        val character = Donut()
        val looker = mockk<Looker>()
        val lookable = Moon()

        every { looker.getSeenObjects(lookable) } returns "Салам"

        val context = character.look(looker, lookable)
        assertTrue { context.getSeenObjects() == "Салам" }
        verify { looker.getSeenObjects(lookable) }
    }

    @Test fun rocketLookerTest() {
        val character = mockk<Character>()
        val speed = 1.0
        val looker = mockk<Looker>()
        val lookable = Moon()
        val rocket = Rocket(arrayOf(character), speed, looker)

        val wantedContext = LookContext(looker, lookable)
        every { character.look(looker, lookable) } returns wantedContext

        val actualContext = rocket.getCrewMember(0).look(looker, lookable)
        assertEquals(wantedContext, actualContext)
    }
}
