--- Хэммонд брал его с собой на все эти переговоры по сбору денег в свой фонд.

SELECT 
  N.ID AS NEG_ID, 
  S.ID AS SCIENTIST, 
  S.NAME, 
  F.ID AS FUND_ID 
FROM 
  NEGOTIATIONS AS N 
  LEFT JOIN NEGOTIATIONS_PARTICIPANTS AS NP ON N.ID = NP.NEG_ID 
  LEFT JOIN SCIENTISTS AS S ON NP.SCIENTIST_ID = S.ID 
  INNER JOIN FUNDS AS F ON F.OWNER = S.ID;

--- Как правило, Дженнаро вносил в комнату клетку, покрытую небольшим одеялом, как заварочный чайник с чехлом,

SELECT 
  NEG_ID, 
  S.NAME AS NAME, 
  A.DESCRIPTION, 
  C.ID AS CAGE_ID, 
  T.DESCRIPTION AS CAGE_LOOKS_LIKE, 
  CREATURES.NAME 
FROM 
  ACTIONS AS A 
  LEFT JOIN ACTION_SUBJECT AS ASUB ON A.ID = ASUB.ACTION_ID 
  LEFT JOIN SCIENTISTS AS S ON ASUB.SUBJECT_ID = S.ID 
  LEFT JOIN NEGOTIATION_ACTIONS AS NA ON A.ID = NA.ACTION_ID 
  LEFT JOIN NEGOTIATIONS AS N ON NA.NEG_ID = N.ID 
  INNER JOIN ACTION_CAGE_OBJECT AS ACO ON A.ID = ACO.ACTION_ID 
  INNER JOIN CAGES AS C ON ACO.CAGE_ID = C.ID 
  INNER JOIN CAGE_LOOKS_LIKE AS CLL ON C.ID = CLL.CAGE_ID 
  LEFT JOIN THINGS AS T ON CLL.THING_ID = T.ID 
  LEFT JOIN CREATURES ON C.CREATURE_ID = CREATURES.ID 
WHERE 
  S.ID = 2 AND A.ID=1;

--- и Хэммонд произносил свою обычную речь о перспективах развития так называемой "биологической потребительской продукции".

SELECT 
  NEG_ID, 
  S.NAME AS NAME, 
  A.DESCRIPTION
FROM 
  ACTIONS AS A 
  LEFT JOIN ACTION_SUBJECT AS ASUB ON A.ID = ASUB.ACTION_ID 
  LEFT JOIN SCIENTISTS AS S ON ASUB.SUBJECT_ID = S.ID 
  LEFT JOIN NEGOTIATION_ACTIONS AS NA ON A.ID = NA.ACTION_ID 
  LEFT JOIN NEGOTIATIONS AS N ON NA.NEG_ID = N.ID 
WHERE 
  S.ID = 1 AND A.ID=2;

--- Затем в самый патетический момент речи он срывал одеяло с клетки, и слон представал перед глазами собравшихся.

SELECT 
  NEG_ID, 
  S.NAME AS NAME, 
  A.DESCRIPTION, 
  CAGES.ID AS CAGE_ID, 
  T.DESCRIPTION AS CAGE_COVERED_WITH, 
  CREATURES.NAME 
FROM 
  ACTIONS AS A 
  LEFT JOIN ACTION_SUBJECT AS ASUB ON A.ID = ASUB.ACTION_ID 
  LEFT JOIN SCIENTISTS AS S ON ASUB.SUBJECT_ID = S.ID 
  LEFT JOIN NEGOTIATION_ACTIONS AS NA ON A.ID = NA.ACTION_ID 
  LEFT JOIN NEGOTIATIONS AS N ON NA.NEG_ID = N.ID 
  INNER JOIN ACTION_THING_OBJECT AS ATO ON A.ID = ATO.ACTION_ID 
  INNER JOIN THINGS AS T ON T.ID = ATO.THING_ID
  INNER JOIN CAGE_COVERED_WITH AS CCW ON CCW.THING_ID = T.ID
  INNER JOIN CAGES ON CCW.CAGE_ID = CAGES.ID
  INNER JOIN CREATURES ON CAGES.CREATURE_ID = CREATURES.ID;

--- И тут Хэммонд просил денег.

SELECT 
  NEG_ID, 
  S.NAME AS NAME, 
  A.DESCRIPTION
FROM 
  ACTIONS AS A 
  LEFT JOIN ACTION_SUBJECT AS ASUB ON A.ID = ASUB.ACTION_ID 
  LEFT JOIN SCIENTISTS AS S ON ASUB.SUBJECT_ID = S.ID 
  LEFT JOIN NEGOTIATION_ACTIONS AS NA ON A.ID = NA.ACTION_ID 
  LEFT JOIN NEGOTIATIONS AS N ON NA.NEG_ID = N.ID 
WHERE 
  S.ID = 1 AND A.ID=4;

