CREATE TABLE SCIENTISTS(
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(50)
);

CREATE TABLE HUMANS(
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(50)
);

CREATE TABLE FUNDS(
  ID SERIAL PRIMARY KEY,
  OWNER INTEGER REFERENCES SCIENTISTS(ID)
);

CREATE TABLE NEGOTIATIONS(
  ID SERIAL PRIMARY KEY,
  TIME_START TIMESTAMP,
  TIME_END TIMESTAMP
);

CREATE TABLE NEGOTIATIONS_PARTICIPANTS(
  NEG_ID INTEGER REFERENCES NEGOTIATIONS(ID),
  SCIENTIST_ID INTEGER REFERENCES SCIENTISTS(ID),
  PRIMARY KEY(NEG_ID, SCIENTIST_ID)
);

CREATE TABLE NEGOTIATION_HUMAN_PARTICIPANTS(
  NEG_ID INTEGER REFERENCES NEGOTIATIONS(ID),
  HUMAN_ID INTEGER REFERENCES HUMANS(ID),
  PRIMARY KEY(NEG_ID, HUMAN_ID)
);
  


CREATE TABLE ACTIONS(
  ID SERIAL PRIMARY KEY,
  DESCRIPTION TEXT,
  TIME_START TIMESTAMP,
  TIME_END TIMESTAMP
);

CREATE TABLE ACTION_MOMENTS(
  ID SERIAL PRIMARY KEY,
  ACTION_ID INTEGER REFERENCES ACTIONS(ID),
  DESCRIPTION TEXT,
  TIME TIMESTAMP
);

CREATE TABLE NEGOTIATION_ACTIONS(
  NEG_ID INTEGER REFERENCES NEGOTIATIONS(ID),
  ACTION_ID INTEGER REFERENCES ACTIONS(ID),
  PRIMARY KEY(NEG_ID, ACTION_ID)
);

CREATE TABLE ACTION_SUBJECT(
  ACTION_ID INTEGER REFERENCES ACTIONS(ID),
  SUBJECT_ID INTEGER REFERENCES SCIENTISTS(ID),
  PRIMARY KEY(ACTION_ID, SUBJECT_ID)
);

CREATE TABLE CREATURES(
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(50),
  CREATION_DATE TIMESTAMP DEFAULT NOW()
);

CREATE TABLE CREATURE_CREATORS(
  CREATURE_ID INTEGER REFERENCES CREATURES(ID),
  SCIENTIST_ID INTEGER REFERENCES SCIENTISTS(ID),
  PRIMARY KEY(CREATURE_ID, SCIENTIST_ID)
);


CREATE TABLE CAGES(
  ID SERIAL PRIMARY KEY,
  CREATURE_ID INTEGER REFERENCES CREATURES(ID) NOT NULL,
  UNIQUE(CREATURE_ID)
);

CREATE TABLE ACTION_CAGE_OBJECT(
  ACTION_ID INTEGER REFERENCES ACTIONS(ID),
  CAGE_ID INTEGER REFERENCES CAGES(ID),
  PRIMARY KEY(ACTION_ID, CAGE_ID)
);

CREATE TABLE THINGS(
  ID SERIAL PRIMARY KEY,
  DESCRIPTION TEXT
);


CREATE TABLE ACTION_THING_OBJECT(
  ACTION_ID INTEGER REFERENCES ACTIONS(ID),
  THING_ID INTEGER REFERENCES THINGS(ID),
  PRIMARY KEY (ACTION_ID, THING_ID)
);

CREATE TABLE CAGE_LOOKS_LIKE(
  CAGE_ID INTEGER REFERENCES CAGES(ID),
  THING_ID INTEGER REFERENCES THINGS(ID),
  PRIMARY KEY (CAGE_ID, THING_ID)
);

CREATE TABLE CAGE_COVERED_WITH(
  CAGE_ID INTEGER REFERENCES CAGES(ID),
  THING_ID INTEGER REFERENCES THINGS(ID),
  PRIMARY KEY(CAGE_ID, THING_ID)
);

--- FILL WITH DATA
INSERT INTO SCIENTISTS(NAME) VALUES ('Hammond'), ('Gennaro');
INSERT INTO CREATURES(NAME) VALUES ('Elephant');

INSERT INTO CREATURE_CREATORS(CREATURE_ID, SCIENTIST_ID) VALUES (1, 1), (1,2);

INSERT INTO CAGES(CREATURE_ID) VALUES (1);

INSERT INTO THINGS(DESCRIPTION) VALUES ('небольшое одеяло');
INSERT INTO CAGE_COVERED_WITH(CAGE_ID, THING_ID) VALUES (1,1);

INSERT INTO THINGS(DESCRIPTION) VALUES('заварочный чайник с чехлом');
INSERT INTO CAGE_LOOKS_LIKE(CAGE_ID, THING_ID) VALUES (1, 2);

INSERT INTO ACTIONS(DESCRIPTION, TIME_START, TIME_END) VALUES ('внести в комнату клетку', now(), now() + interval '30 seconds'), ('произнести речь', now(), now() + interval '3 minutes'), ('сорвать одеяло', now() + interval '120 seconds', now() + interval '121 seconds'), ('просить денег', now() + interval '160 seconds', now() + interval '180 seconds');
INSERT INTO ACTION_SUBJECT(ACTION_ID, SUBJECT_ID) VALUES (1, 2); --- Дженнаро вносит клетку
INSERT INTO ACTION_SUBJECT(ACTION_ID, SUBJECT_ID) VALUES (2, 1); --- Хэммонд произносит речь
INSERT INTO ACTION_SUBJECT(ACTION_ID, SUBJECT_ID) VALUES (3, 1); --- Хэммонд срывает одеяло
INSERT INTO ACTION_SUBJECT(ACTION_ID, SUBJECT_ID) VALUES (4, 1); --- Хэммонд просит денег

INSERT INTO ACTION_MOMENTS(ACTION_ID, DESCRIPTION, TIME) VALUES (2, 'самый патетический момент речи', now() + interval '120');

INSERT INTO ACTION_CAGE_OBJECT(ACTION_ID, CAGE_ID) VALUES (1, 1);
INSERT INTO ACTION_THING_OBJECT(ACTION_ID, THING_ID) VALUES (3, 1);

INSERT INTO NEGOTIATIONS(TIME_START, TIME_END) VALUES (NOW(), NOW());
INSERT INTO NEGOTIATIONS_PARTICIPANTS(NEG_ID, SCIENTIST_ID) VALUES (1, 1), (1, 2);

INSERT INTO NEGOTIATION_ACTIONS(NEG_ID, ACTION_ID) VALUES (1, 1), (1, 2), (1, 3), (1, 4);

INSERT INTO FUNDS(OWNER) VALUES (1);

INSERT INTO HUMANS(NAME) VALUES ('Вася'), ('Петя');
INSERT INTO NEGOTIATION_HUMAN_PARTICIPANTS(HUMAN_ID, NEG_ID) VALUES (1, 1), (2, 1);
