CREATE TABLE SCIENTISTS (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(32),
  SALARY INTEGER
);

CREATE TABLE CREATURES (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(32),
  CREATION_DATE TIMESTAMP
);

CREATE TABLE CAGE (
  ID SERIAL PRIMARY KEY,
  CREATURE_ID INTEGER REFERENCES CREATURES(ID),
  MATERIAL VARCHAR(32),
  SIZE INTEGER,
  UNIQUE(CREATURE_ID)
);

CREATE TABLE CREATURE_CREATORS(
  CREATURE_ID INTEGER REFERENCES CREATURES(ID),
  SCIENTIST_ID INTEGER REFERENCES SCIENTISTS(ID),
  UNIQUE(CREATURE_ID, SCIENTIST_ID)
);

INSERT INTO SCIENTISTS(name, salary) VALUES ('hammond', 1000000), ('gennaro', 0);
INSERT INTO CREATURES(name, creation_date) VALUES ('elephant', now()), ('raptor', now());
INSERT INTO CREATURE_CREATORS(CREATURE_ID, SCIENTIST_ID) VALUES (1, 1), (1,2), (2,2);
INSERT INTO CAGE(CREATURE_ID, MATERIAL, SIZE) VALUES (1, 'carbon', 5), (2, 'metal', 10);
