/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("lab7.kotlin-application-conventions")
}

dependencies {
    implementation(project(":shared"))
}

application {
    // Define the main class for the application.
    mainClass.set("lab7.client.AppKt")
}
