/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("lab8.kotlin-application-conventions")
    id("org.jetbrains.compose") version "1.3.1"
}

repositories {
    mavenCentral()
    maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
}

dependencies {
    val koin_version = "3.4.0"

    implementation(project(":shared"))
    implementation(compose.desktop.currentOs)

    // https://mvnrepository.com/artifact/io.insert-koin/koin-core
    runtimeOnly("io.insert-koin:koin-core:$koin_version")

    // https://mvnrepository.com/artifact/io.insert-koin/koin-core-jvm
    implementation("io.insert-koin:koin-core-jvm:$koin_version")

    val voyagerVersion = "1.0.0-rc04"
    implementation("cafe.adriel.voyager:voyager-navigator:$voyagerVersion")
}

application {
    // Define the main class for the application.
    mainClass.set("lab8.client.AppKt")
}
