import org.jetbrains.compose.desktop.application.dsl.TargetFormat

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // id("lab8.kotlin-application-conventions")
    kotlin("jvm")
    id("org.jetbrains.compose") version "1.3.1"
}

repositories {
    mavenCentral()
    maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
}

buildscript {
    repositories {
        mavenCentral()
    }
}

dependencies {
    val koin_version = "3.4.0"

    implementation(project(":shared"))
    implementation(compose.desktop.currentOs)

    // https://mvnrepository.com/artifact/io.insert-koin/koin-core
    runtimeOnly("io.insert-koin:koin-core:$koin_version")

    // https://mvnrepository.com/artifact/io.insert-koin/koin-core-jvm
    implementation("io.insert-koin:koin-core-jvm:$koin_version")

    val voyagerVersion = "1.0.0-rc04"
    implementation("cafe.adriel.voyager:voyager-navigator:$voyagerVersion")


    implementation("org.jetbrains.compose.material:material-icons-extended-desktop:1.3.1")


    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4")
    // https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-core-jvm
    runtimeOnly("org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.4")


    // https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api
    implementation("org.apache.logging.log4j:log4j-api:2.20.0")

    // https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core
    implementation("org.apache.logging.log4j:log4j-core:2.20.0")

    // https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api-kotlin
    implementation("org.apache.logging.log4j:log4j-api-kotlin:1.2.0")
}

compose.desktop {
    application {
        mainClass = "lab8.client.AppKt"

        buildTypes.release.proguard {
            obfuscate.set(true)
        }

        nativeDistributions {
            targetFormats(TargetFormat.Rpm)
        }
    }
}