# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schedule.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eschedule.proto\"$\n\x04Time\x12\x0c\n\x04hour\x18\x01 \x02(\x05\x12\x0e\n\x06minute\x18\x02 \x02(\x05\"6\n\nLessonTime\x12\x14\n\x05start\x18\x01 \x02(\x0b\x32\x05.Time\x12\x12\n\x03\x65nd\x18\x02 \x02(\x0b\x32\x05.Time\"\x94\x01\n\x06Lesson\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0f\n\x07teacher\x18\x02 \x02(\t\x12\x10\n\x08week_day\x18\x03 \x02(\t\x12\x11\n\x05weeks\x18\x04 \x03(\x05\x42\x02\x10\x01\x12\x1d\n\x06\x66ormat\x18\x05 \x02(\x0e\x32\r.LessonFormat\x12\x19\n\x04time\x18\x06 \x02(\x0b\x32\x0b.LessonTime\x12\x0c\n\x04room\x18\x07 \x01(\t\"$\n\x08Schedule\x12\x18\n\x07lessons\x18\x01 \x03(\x0b\x32\x07.Lesson*2\n\x0cLessonFormat\x12\n\n\x06REMOTE\x10\x00\x12\x0c\n\x08ON_PLACE\x10\x01\x12\x08\n\x04\x42OTH\x10\x02')

_LESSONFORMAT = DESCRIPTOR.enum_types_by_name['LessonFormat']
LessonFormat = enum_type_wrapper.EnumTypeWrapper(_LESSONFORMAT)
REMOTE = 0
ON_PLACE = 1
BOTH = 2


_TIME = DESCRIPTOR.message_types_by_name['Time']
_LESSONTIME = DESCRIPTOR.message_types_by_name['LessonTime']
_LESSON = DESCRIPTOR.message_types_by_name['Lesson']
_SCHEDULE = DESCRIPTOR.message_types_by_name['Schedule']
Time = _reflection.GeneratedProtocolMessageType('Time', (_message.Message,), {
  'DESCRIPTOR' : _TIME,
  '__module__' : 'schedule_pb2'
  # @@protoc_insertion_point(class_scope:Time)
  })
_sym_db.RegisterMessage(Time)

LessonTime = _reflection.GeneratedProtocolMessageType('LessonTime', (_message.Message,), {
  'DESCRIPTOR' : _LESSONTIME,
  '__module__' : 'schedule_pb2'
  # @@protoc_insertion_point(class_scope:LessonTime)
  })
_sym_db.RegisterMessage(LessonTime)

Lesson = _reflection.GeneratedProtocolMessageType('Lesson', (_message.Message,), {
  'DESCRIPTOR' : _LESSON,
  '__module__' : 'schedule_pb2'
  # @@protoc_insertion_point(class_scope:Lesson)
  })
_sym_db.RegisterMessage(Lesson)

Schedule = _reflection.GeneratedProtocolMessageType('Schedule', (_message.Message,), {
  'DESCRIPTOR' : _SCHEDULE,
  '__module__' : 'schedule_pb2'
  # @@protoc_insertion_point(class_scope:Schedule)
  })
_sym_db.RegisterMessage(Schedule)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LESSON.fields_by_name['weeks']._options = None
  _LESSON.fields_by_name['weeks']._serialized_options = b'\020\001'
  _LESSONFORMAT._serialized_start=301
  _LESSONFORMAT._serialized_end=351
  _TIME._serialized_start=18
  _TIME._serialized_end=54
  _LESSONTIME._serialized_start=56
  _LESSONTIME._serialized_end=110
  _LESSON._serialized_start=113
  _LESSON._serialized_end=261
  _SCHEDULE._serialized_start=263
  _SCHEDULE._serialized_end=299
# @@protoc_insertion_point(module_scope)
